### ISSUE TITLE
Unable to launch Cypress after upgrading to cypress-ntlm-auth 3.0.0

### ISSUE THREAD

**Issue by hari49951** [bjowes/cypress-ntlm-auth#134]
Hi @bjowes,

I updated cypress-ntlm-auth plugin to v3.0.0 and trying to open cypress but getting below error. Could you please guide me If I am missing anything?

Cypress v4.8.0
baseUrl mentioned in cypress.josn

plugins/index.js file:
module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
  return config
};

support/index.js file:
import "cypress-ntlm-auth/dist/commands"

Error:
C:\Users\cypress> npx cypress-ntlm open
Cannot read property 'parseRunArguments' of undefined
TypeError: Cannot read property 'parseRunArguments' of undefined
    at CypressFacade.<anonymous> (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\cypress.facade.js:50:44)
    at Generator.next (<anonymous>)
    at C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\cypress.facade.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\cypress.facade.js:13:12)
    at CypressFacade.parseRunArguments (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\cypress.facade.js:49:16)
    at Startup.<anonymous> (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\startup.js:67:46)
    at Generator.next (<anonymous>)
    at C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\startup.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\startup.js:16:12)
    at Startup.prepareOptions (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\startup\startup.js:61:16)
    at Object.<anonymous> (C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\index.js:56:30)
    at Generator.next (<anonymous>)
    at C:\Users\cypress\node_modules\cypress-ntlm-auth\dist\index.js:8:71
    at new Promise (<anonymous>)

**Comment by bjowes** [comment]
Hi @hari49951 - please upgrade cypress to latest version. The parseRunArguments method was added in cypress 4.11.0, but I run my own tests of the plugin with cypress 5.3.0.

**Comment by hari49951** [comment]
Thank you @bjowes for quick reply.
