### ISSUE TITLE
While running ntlm-proxy it gives this issue: TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by MuhammadJawad1214** [bjowes/cypress-ntlm-auth#217]
Before it was working correctly But by today one hour before it is giving me this error.
Please help me out @bjowes 

The complete log is as follows

node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:640:5)
    at Environment.portFromUrl (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\environment.js:70:24)
    at Environment.get configApiPort [as configApiPort] (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\environment.js:24:21)
    at Startup.<anonymous> (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\startup.js:98:150)
    at Generator.next (<anonymous>)
    at C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\startup.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\startup.js:16:12)        
    at Startup.startNtlmProxy (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\startup\startup.js:94:16)
    at C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\index.js:75:37
    at Generator.next (<anonymous>)
    at C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\projects\cypress-cucumber-typeScript\node_modules\cypress-ntlm-auth\dist\index.js:4:12) {
  input: '127.0.0.1:64059',
  code: 'ERR_INVALID_URL'
}

**Comment by MuhammadJawad1214** [comment]
@bjowes can you please help regarding to this, i have tried delete node_modules and reinstall the node modules along with the ntlm plugin, I have restart the machine as well But still having this issue

**Comment by bjowes** [comment]
If the tests stop working from one day to the next, without any changes made, the most likely issue is that versions of the software has changed. Candidates: 
- NodeJS upgraded 
- npm packages upgraded
I presume your tests run in some CI environment. The `npm install` command may install newer versions of packages if they match the version requirements in package.json.

**Comment by bjowes** [comment]
From the error log it looks like you are specifying the Config API url through environment variables. Older versions of this plugin (and NodeJs) may have accepted the form `127.0.0.1:64059`, but now you need to specify a complete URL, for this example `http://127.0.0.1:64059`. If you have such environment variables, please update them

**Comment by MuhammadJawad1214** [comment]
It works by setting the environment variable with the url starting with http://, Thanks @bjowes
