### ISSUE TITLE
Unable to start cypress-ntlm on Jenkins - 'ERR_INVALID_URL'

### ISSUE THREAD

**Issue by sham-christopher** [bjowes/cypress-ntlm-auth#254]
Hello,

I am trying to run Cypress tests on Jenkins but I always get the following error.
` + DEBUG=cypress:plugin:ntlm-auth
+ npx cypress-ntlm run --env TAGS=@aite-dqp
2024-04-15T19:29:35.091Z cypress:plugin:ntlm-auth Adding 127.0.0.1 to NO_PROXY to disable loopback proxying
2024-04-15T19:29:35.092Z cypress:plugin:ntlm-auth Starting ntlm-proxy...
2024-04-15T19:29:35.093Z cypress:plugin:ntlm-auth Could not start ntlm-proxy
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at /home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/upstream.proxy.manager.js:25:28
    at Array.map (<anonymous>)
    at UpstreamProxyManager.init (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/upstream.proxy.manager.js:22:52)
    at CoreServer.<anonymous> (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/core.server.js:40:40)
    at Generator.next (<anonymous>)
    at /home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/core.server.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/core.server.js:16:12)
    at CoreServer.start (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/core.server.js:39:16)
    at Main.<anonymous> (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/main.js:35:54)
    at Generator.next (<anonymous>)
    at /home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/main.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jenkins/workspace/ASK_Cypress_Tests/ask-ui/src/main/webapp/ask-web-ui/node_modules/cypress-ntlm-auth/dist/proxy/main.js:16:12) {
  input: 'http://::1/',
  code: 'ERR_INVALID_URL'
} `

I don't get the error while running on my machine. The error talks about an input that was provided "http://::1/" and I have no idea why. 

My versions are 

cypress-ntlm-auth: 4.1.5
cypress: 13.7.0

**Comment by bjowes** [comment]
This error comes from the fact that localhost is resolved differently on different systems. It used to be 127.0.0.1 but as IPv6 is slowly getting more adoption it is changing to `::1` on some systems. Which OS is Jenkins running on?

In this particular case, it seems that the NO_PROXY environment variable is set before cypress-ntlm is launched, and it contains the `::1` string. Check the contents of NO_PROXY, there may be something there you want to preserve. You could try setting NO_PROXY manually to blank before starting cypress-ntlm. 

A proper fix would require that the `::1` string is detected by cypress-ntlm and that is it escaped as `[::1]` - this is already implemented in other areas of cypress-ntlm.

**Comment by sham-christopher** [comment]
Thanks a lot. That fixed the issue. I have another one but I will raise it in another.
