### ISSUE TITLE
Query regarding installing this plugin

### ISSUE THREAD

**Issue by krishvv** [bjowes/cypress-ntlm-auth#26]
@bjowes . Thanks for the plugin . I followed the steps for installing the plugin. When i execute
npm run cypress-ntlm I am getting the following error
=====
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'cypress/lib/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Test\ntml-auth\node_modules\cypress-ntlm-auth\src\launcher\cypressNtlm.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
=======================
1.Only doing an npm install --save-dev cypress-ntlm-auth is sufficient?

**Comment by krishvv** [comment]
Should i do an npm install of this plugin on top of the existing cypress? Also where should i place the cloned folder of this plugin?

**Comment by krishvv** [comment]
@bjowes - Thanks . I re did everything and it is working fine . :)

**Comment by bjowes** [comment]
Ok, glad that it worked out!
